name: Caller Workflow

on: workflow_dispatch

jobs:
  calling-workflow:
    uses: SnykTestOrg1/ci-template/blob/main/.github/workflows/snyk-template.yml@main  # Specify repo and branch
    with:
      flag: "--all-projects"
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
