name: Caller Workflow

on: workflow_dispatch

jobs:
  calling-workflow:
    uses: hung-snyk/ci-template/.github/workflows/GHA-template.yml@main  # Specify repo and branch
    with:
      flag: "monitor"
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
